<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="parameters">

  <xacro:property name="chassis_L" value="2.0"/>
  <xacro:property name="chassis_W" value="0.5"/>
  <xacro:property name="chassis_H" value="0.10"/>
  <xacro:property name="chassis_M" value="400"/>


  <!-- Degree-to-radian conversions -->
  <xacro:property name="degrees_45" value="0.785398163"/>
  <xacro:property name="degrees_90" value="1.57079633"/>

  <xacro:property name="wheel_travel_front" value="0.208"/>

  <xacro:property name="front_axle_L" value="0.10"/>
  <xacro:property name="front_axle_W" value="0.8"/>
  <xacro:property name="front_axle_H" value="0.10"/>
  <xacro:property name="front_axle_M" value="10"/>


  <xacro:property name="shock_upper_R" value="0.10"/>
  <xacro:property name="shock_upper_H" value="${front_axle_H}"/>
  <xacro:property name="shock_upper_M" value="3"/>


  <xacro:property name="shock_lower_R" value="${shock_upper_R/2}"/>
  <xacro:property name="shock_lower_H" value="${wheel_travel_front+1/2*front_axle_H}"/>
  <xacro:property name="shock_lower_M" value="1"/>


  <xacro:property name="steer_link_R" value="0.05"/>
  <xacro:property name="steer_link_H" value="0.10"/>
  <xacro:property name="steer_link_M" value="1"/>


  <xacro:property name="wheel_front_R" value="0.32"/>
  <xacro:property name="wheel_front_H" value="0.20"/>
  <xacro:property name="wheel_front_M" value="3"/>





  <xacro:property name="wheel_travel_rear" value="0.208"/>

  <xacro:property name="rear_axle_L" value="0.10"/>
  <xacro:property name="rear_axle_W" value="0.8"/>
  <xacro:property name="rear_axle_H" value="0.10"/>
  <xacro:property name="rear_axle_M" value="10"/>

  <xacro:property name="wheel_rear_R" value="0.32"/>
  <xacro:property name="wheel_rear_H" value="0.20"/>
  <xacro:property name="wheel_rear_M" value="3"/>

  <xacro:property name="shock_wall_thickness" value="0.01"/>

  <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N.
       shock_stroke is 0.028575 meters. shock_spring_constant, an approximation
       of a Traxxas Ultra Shock shock absorber spring's constant, is
       437.817 N/m. -->
  <xacro:property name="shock_eff_limit" value="2000"/>
  <xacro:property name="shock_vel_limit" value="100"/>

  <!-- The specifications for a Titan(R) 550 motor could not be found, so the
       stall torque of a Mabuchi Motor(R) RS-550VC-7525 motor was used instead.

       num_spur_gear_teeth = 68
       num_pinion_gear_teeth = 19
       final_gear_ratio = (num_spur_gear_teeth / num_pinion_gear_teeth) *
         5.22 = 18.68
       stall_torque = 0.549 N m
       axle_eff_limit = ((2 * stall_torque) * final_gear_ratio) / 4 =
         5.12766 N m

       max_speed = 40 mph (30+ mph) = 17.8816 m/s
       axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_dia)) =
         244.8696 rad/s -->
  <xacro:property name="axle_eff_limit" value="259"/>
  <xacro:property name="axle_vel_limit" value="56.25"/>

  <!-- These constants are used to simulate a Traxxas 2056 servo operated at
       6 V. servo_stall_torque is measured in N m. servo_no_load_speed is
       measured in rad/s. -->
  <xacro:property name="steer_stall_torque" value="1000"/>
  <xacro:property name="steer_no_load_speed" value="4.553"/>



</robot>
