<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="front_axle_assembly">

  <!-- Degree-to-radian conversions -->
  <xacro:property name="degrees_45" value="0.785398163"/>
  <xacro:property name="degrees_90" value="1.57079633"/>

  <xacro:property name="wheel_travel_front" value="0.208"/>

  <xacro:property name="front_axle_L" value="0.10"/>
  <xacro:property name="front_axle_W" value="1.12"/>
  <xacro:property name="front_axle_H" value="0.10"/>
  <xacro:property name="front_axle_M" value="10"/>


  <xacro:property name="shock_upper_R" value="0.10"/>
  <xacro:property name="shock_upper_H" value="${front_axle_H}"/>
  <xacro:property name="shock_upper_M" value="3"/>


  <xacro:property name="shock_lower_R" value="${shock_upper_R/2}"/>
  <xacro:property name="shock_lower_H" value="${wheel_travel_front+1/2*front_axle_H}"/>
  <xacro:property name="shock_lower_M" value="1"/>


  <xacro:property name="steer_link_R" value="0.05"/>
  <xacro:property name="steer_link_H" value="0.20"/>
  <xacro:property name="steer_link_M" value="1"/>


  <xacro:property name="wheel_front_R" value="0.32"/>
  <xacro:property name="wheel_front_H" value="0.20"/>
  <xacro:property name="wheel_front_M" value="3"/>

  <xacro:property name="shock_wall_thickness" value="0.01"/>

  <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N.
       shock_stroke is 0.028575 meters. shock_spring_constant, an approximation
       of a Traxxas Ultra Shock shock absorber spring's constant, is
       437.817 N/m. -->
  <xacro:property name="shock_eff_limit" value="20"/>
  <xacro:property name="shock_vel_limit" value="1000"/>

  <!-- The specifications for a Titan(R) 550 motor could not be found, so the
       stall torque of a Mabuchi Motor(R) RS-550VC-7525 motor was used instead.

       num_spur_gear_teeth = 68
       num_pinion_gear_teeth = 19
       final_gear_ratio = (num_spur_gear_teeth / num_pinion_gear_teeth) *
         5.22 = 18.68
       stall_torque = 0.549 N m
       axle_eff_limit = ((2 * stall_torque) * final_gear_ratio) / 4 =
         5.12766 N m

       max_speed = 40 mph (30+ mph) = 17.8816 m/s
       axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_dia)) =
         244.8696 rad/s -->
  <xacro:property name="axle_eff_limit" value="100"/>
  <xacro:property name="axle_vel_limit" value="244.8696"/>

  <!-- These constants are used to simulate a Traxxas 2056 servo operated at
       6 V. servo_stall_torque is measured in N m. servo_no_load_speed is
       measured in rad/s. -->
  <xacro:property name="steer_stall_torque" value="50"/>
  <xacro:property name="steer_no_load_speed" value="4.553"/>



  <!-- Inertia of a solid cuboid. Width is measured along the x axis, depth
       along the y axis, and height along the z axis. -->
  <xacro:macro name="solid_cuboid_inertial"
               params="width depth height mass">
    <inertial>
      <mass value="${mass}"/>
      <origin/>
      <inertia ixx="${mass * (depth * depth + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (width * width + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + depth * depth) / 12}"/>
    </inertial>
  </xacro:macro>

  <!-- Inertia of a thick-walled cylindrical tube with open ends. Height is
       measured along the z axis, which is the tube's axis. inner_rad and
       outer_rad are the tube's inner and outer radii, respectively. -->
  <xacro:macro name="thick_walled_tube_inertial"
               params="inner_rad outer_rad height mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${(1 / 12) * mass * (3 * (inner_rad * inner_rad +
                    outer_rad * outer_rad) + height * height)}"
               ixy="0" ixz="0"
               iyy="${(1 / 12) * mass * (3 * (inner_rad * inner_rad +
                    outer_rad * outer_rad) + height * height)}"
               iyz="0"
               izz="${mass * (inner_rad * inner_rad +
                    outer_rad * outer_rad) / 2}"/>
    </inertial>
  </xacro:macro>



  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="front_axle"/>
    <origin xyz="0 0 1" />
  </joint>


  <!-- front_axle-->
    <link name="front_axle">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${front_axle_L} ${front_axle_W} ${front_axle_H}"/>
        </geometry>
        <material name="mat_1"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${front_axle_L} ${front_axle_W} ${front_axle_H}"/>
        </geometry>
      </collision>

      <xacro:solid_cuboid_inertial
         width="${front_axle_L}" depth="${front_axle_W}"
         height="${front_axle_H}" mass="${front_axle_M}">
      </xacro:solid_cuboid_inertial>
    </link>

  <!-- shock_upper_front_left -->
    <link name="shock_upper_front_left">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_upper_R}" length="${shock_upper_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_upper_R}" length="${shock_upper_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${shock_upper_R - shock_wall_thickness}" outer_rad="${shock_upper_R}"
          height="${shock_upper_H}" mass="${shock_upper_M}"/>
    </link>

  <!-- JOINT shock_upper_front_left TO front_axle -->
    <joint name="shock_front_left_to_front_axle_joint" type="fixed">
      <parent link="front_axle"/>
      <child link="shock_upper_front_left"/>
      <origin xyz="0 ${front_axle_W/2} 0"/>
    </joint>



  <!-- shock_upper_front_right -->
    <link name="shock_upper_front_right">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_upper_R}" length="${shock_upper_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_upper_R}" length="${shock_upper_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${shock_upper_R - shock_wall_thickness}" outer_rad="${shock_upper_R}"
          height="${shock_upper_H}" mass="${shock_upper_M}"/>
    </link>

  <!-- JOINT shock_upper_front_right TO front_axle -->
    <joint name="shock_front_right_to_front_axle_joint" type="fixed">
      <parent link="front_axle"/>
      <child link="shock_upper_front_right"/>
      <origin xyz="0 ${-front_axle_W/2} 0"/>
    </joint>


  <!-- shock_lower_front_left -->
    <link name="shock_lower_front_left">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_lower_R}" length="${shock_lower_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_lower_R}" length="${shock_lower_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${shock_lower_R - shock_wall_thickness}" outer_rad="${shock_lower_R}"
          height="${shock_lower_H}" mass="${shock_lower_M}"/>
    </link>  

  <!-- JOINT shock_lower_front_left TO shock_upper_front_left -->
    <joint name="shock_front_left_upper_to_lower_joint" type="prismatic">
      <parent link="shock_upper_front_left"/>
      <child link="shock_lower_front_left"/>
      <origin xyz="0 0 ${-shock_lower_H/2 + 1/2*front_axle_H}"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${wheel_travel_front}"
             effort="${shock_eff_limit}" velocity="${shock_vel_limit}"/>
    </joint>

    <transmission name="front_left_shock_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="shock_front_left_upper_to_lower_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_left_shock_act">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  <!-- shock_lower_front_right -->
    <link name="shock_lower_front_right">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_lower_R}" length="${shock_lower_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${shock_lower_R}" length="${shock_lower_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${shock_lower_R - shock_wall_thickness}" outer_rad="${shock_lower_R}"
          height="${shock_lower_H}" mass="${shock_lower_M}"/>
    </link>  

  <!-- JOINT shock_lower_front_right TO shock_upper_front_right -->
    <joint name="shock_front_right_upper_to_lower_joint" type="prismatic">
      <parent link="shock_upper_front_right"/>
      <child link="shock_lower_front_right"/>
      <origin xyz="0 0 ${-shock_lower_H/2 + 1/2*front_axle_H}"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="${wheel_travel_front}"
             effort="${shock_eff_limit}" velocity="${shock_vel_limit}"/>
    </joint>

    <transmission name="front_right_shock_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="shock_front_right_upper_to_lower_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_right_shock_act">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  <!-- steer_link_front_left -->
    <link name="steer_link_front_left">
      <visual>
        <origin xyz="0 ${steer_link_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${steer_link_R}" length="${steer_link_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${steer_link_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${steer_link_R}" length="${steer_link_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${steer_link_R - shock_wall_thickness}" outer_rad="${steer_link_R}"
          height="${steer_link_H}" mass="${steer_link_M}"/>
    </link>

  <!-- JOINT steer_link_front_left TO shock_lower_front_left -->
    <joint name="steer_front_left_joint" type="revolute">
      <parent link="shock_lower_front_left"/>
      <child link="steer_link_front_left"/>
      <origin xyz="0 0 ${-shock_lower_H/2 + steer_link_R}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-degrees_45}" upper="${degrees_45}"
             effort="${steer_stall_torque}" velocity="${steer_no_load_speed}"/>
    </joint>

    <transmission name="front_left_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="steer_front_left_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_left_steering_act">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  <!-- steer_link_front_right -->
    <link name="steer_link_front_right">
      <visual>
        <origin xyz="0 ${-steer_link_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${steer_link_R}" length="${steer_link_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
        <geometry>
        <origin xyz="0 ${-steer_link_H/2} 0" rpy="${degrees_90} 0 0"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${steer_link_R - shock_wall_thickness}" outer_rad="${steer_link_R}"
          height="${steer_link_H}" mass="${steer_link_M}"/>
    </link>

  <!-- JOINT steer_link_front_right TO shock_lower_front_right -->
    <joint name="steer_front_right_joint" type="revolute">
      <parent link="shock_lower_front_right"/>
      <child link="steer_link_front_right"/>
      <origin xyz="0 0 ${-shock_lower_H/2 + steer_link_R}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-degrees_45}" upper="${degrees_45}"
             effort="${steer_stall_torque}" velocity="${steer_no_load_speed}"/>
    </joint>

    <transmission name="front_right_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="steering_front_right_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="front_right_steering_act">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  <!-- wheel_front_left -->
    <link name="wheel_front_left">
      <visual>
        <origin xyz="0 ${wheel_front_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_front_R}" length="${wheel_front_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${wheel_front_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_front_R}" length="${wheel_front_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${wheel_front_R - shock_wall_thickness}" outer_rad="${wheel_front_R}"
          height="${wheel_front_H}" mass="${wheel_front_M}"/>
    </link>

  <!-- JOINT wheel_front_left TO steer_link_front_left -->
    <joint name="wheel_front_left_to_steer_link_joint" type="continuous">
      <parent link="steer_link_front_left"/>
      <child link="wheel_front_left"/>
      <origin xyz="0 ${steer_link_H} 0 "/>
      <axis xyz="0 1 0"/>
      <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
    </joint>


  <!-- wheel_front_right -->
    <link name="wheel_front_right">
      <visual>
        <origin xyz="0 ${-wheel_front_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_front_R}" length="${wheel_front_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${-wheel_front_H/2} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_front_R}" length="${wheel_front_H}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${wheel_front_R - shock_wall_thickness}" outer_rad="${wheel_front_R}"
          height="${wheel_front_H}" mass="${wheel_front_M}"/>
    </link>

  <!-- JOINT wheel_front_right TO steer_link_front_right -->
    <joint name="wheel_front_right_to_steer_link_joint" type="continuous">
      <parent link="steer_link_front_right"/>
      <child link="wheel_front_right"/>
      <origin xyz="0 ${-steer_link_H} 0 "/>
      <axis xyz="0 1 0"/>
      <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
    </joint>
</robot>
